name: mapperatorinator
services:
    mapperatorinator:
        stdin_open: true
        tty: true
        volumes:
        - .:/workspace/Mapperatorinator
        - ../datasets:/workspace/datasets
        network_mode: host
        container_name: mapperatorinator_space
        shm_size: 8gb
        build: .
        # image: my_fixed_image
        command: /bin/bash
        environment:
          - PROJECT_PATH=/workspace/Mapperatorinator
          - WANDB_API_KEY=${WANDB_API_KEY}

    api:
        build: .
        command: uvicorn api_server:app --host 0.0.0.0 --port 5005
        container_name: mapperatorinator_api
        volumes:
        - .:/workspace/Mapperatorinator
        - ../datasets:/workspace/datasets
        network_mode: host
        shm_size: 8gb
        environment:
          - PROJECT_PATH=/workspace/Mapperatorinator
          - WANDB_API_KEY=${WANDB_API_KEY}
        ports:
          - "5005:5005"
