name: mapperatorinator-cpu
services:
    # Redis缓存服务
    redis:
        image: redis:7-alpine
        container_name: mapperatorinator_redis_cpu
        restart: unless-stopped
        ports:
          - "6379:6379"
        volumes:
          - redis_data:/data
        command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
          interval: 30s
          timeout: 10s
          retries: 3

    # API服务 (仅CPU)
    api:
        build:
          context: .
          dockerfile: Dockerfile.cpu
        command: uvicorn api_v2:app --host 0.0.0.0 --port 8000
        container_name: mapperatorinator_api_cpu
        volumes:
        - .:/workspace/Mapperatorinator
        - ./audio_storage:/workspace/Mapperatorinator/audio_storage
        - ./outputs:/workspace/Mapperatorinator/outputs
        shm_size: 2gb
        environment:
          - PROJECT_PATH=/workspace/Mapperatorinator
          - REDIS_HOST=redis
          - REDIS_PORT=6379
        ports:
          - "8000:8000"
        depends_on:
          redis:
            condition: service_healthy
        restart: unless-stopped

    # Nginx反向代理
    nginx:
        image: nginx:alpine
        container_name: mapperatorinator_nginx
        ports:
          - "80:80"
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
          - api
        restart: unless-stopped

volumes:
  redis_data:
